apiVersion: apps/v1
kind: Deployment
metadata:
  name: key-val-store
spec:
  selector:
    matchLabels:
      app: key-val-store
  template:
    metadata:
      labels:
        app: key-val-store
    spec:
      containers:
        - name: key-val-store
          image: key-val-store
          imagePullPolicy: Never
          resources:
            requests:
              cpu: '0.2'
            limits:
              cpu: '0.2'
---
apiVersion: v1
kind: Service
metadata:
  name: key-val-store
spec:
  selector:
    app: key-val-store
  type: LoadBalancer
  ports:
    - port: 8080
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: key-val-store
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: key-val-store
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 60